/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veterinaria.vistas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import veterinaria.businesslogic.dao.compraDAO;
import veterinaria.businesslogic.dao.productoDAO;
import veterinaria.businesslogic.daolistos.duenoDAO;
import veterinaria.businesslogic.dto.ProductoDTO;

/**
 *
 * @author gabosaurio
 */
public class GUICarrito extends javax.swing.JFrame {
    private static final Logger logger = LogManager.getLogger(GUICarrito.class);
    private List<ProductoDTO> carrito;
    /**
     * Creates new form GUICarrito
     */
    public GUICarrito(List<ProductoDTO> carrito) {
        this.carrito = carrito;
        initComponents();
        setProductosCarrito();
    }
    
    public GUICarrito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productosT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comprarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productosT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Existencia", "Marca", "Precio", "Tipo", "Especie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productosT);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("Carrito");

        comprarBoton.setText("Comprar");
        comprarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBotonActionPerformed(evt);
            }
        });

        cancelarBoton.setText("Cancelar");
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(cancelarBoton)
                        .addGap(18, 18, 18)
                        .addComponent(comprarBoton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprarBoton)
                    .addComponent(cancelarBoton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBotonActionPerformed
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío, agregue cosas al carrito por favor");
        } else {
            compraDAO dao = new compraDAO();
            String telefonoStr = JOptionPane.showInputDialog(this, "Ingrese su número de teléfono");
            if (telefonoStr != null) {
                int idDueno = new duenoDAO().obtenerDuenoPorTelefono(telefonoStr);
                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea realizar la compra?");
                if (confirmacion == 0) {
                    JOptionPane.showMessageDialog(this, "Compra confirmada");
                    for (ProductoDTO i : carrito) {
                    dao.transaccionCompra(idDueno, i.getIdProducto());
                }
                    carrito.clear();
                } else {
                    JOptionPane.showMessageDialog(this, "Compra cancelada");
                }
            }
        }
    }//GEN-LAST:event_comprarBotonActionPerformed

    public void setProductosCarrito() {
        List<ProductoDTO> productos;
        String[] columnas = {"ID", "Nombre", "Existencia", "Marca", "Precio", "Tipo", "Especie" };
        productos = productoDAO.seleccionarTodosLosProductos();
        int fila =  -1;
        DefaultTableModel modelo = null;
        try {
            Object[][] data = new Object[productos.size()][7];
            for (ProductoDTO i : carrito) {
                fila++;
                data[fila][0] = i.getIdProducto();
                data[fila][1] = i.getNombre();
                data[fila][2] = i.getExistencia();
                data[fila][3] = i.getMarca();
                data[fila][4] = i.getPrecio();
                data[fila][5] = i.getTipo();
                data[fila][6] = i.getEspecie();
                modelo = new DefaultTableModel(data, columnas);
            }
        } catch (Exception e) {
            logger.error("Error al cargar tabla", e);
        }
        
        if (modelo == null) {
            JOptionPane.showMessageDialog(this, "Carrito vacío");
        } else {
            productosT.setModel(modelo);
        }
    }
    
    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        GUICompraProductos controlador = new GUICompraProductos(carrito);
        controlador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICarrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JButton comprarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productosT;
    // End of variables declaration//GEN-END:variables
}
